/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    KpiCard: typeof import('./../components/KpiCard.vue')['default']
    Pagination: typeof import('./../components/Pagination.vue')['default']
    PartFormModal: typeof import('./../components/PartFormModal.vue')['default']
    ProductDetailModal: typeof import('./../components/ProductDetailModal.vue')['default']
    ProductFormModal: typeof import('./../components/ProductFormModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./../components/SideMenu.vue')['default']
    StatusBadge: typeof import('./../components/StatusBadge.vue')['default']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    TopBar: typeof import('./../components/TopBar.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
  const IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
  const KpiCard: typeof import('./../components/KpiCard.vue')['default']
  const Pagination: typeof import('./../components/Pagination.vue')['default']
  const PartFormModal: typeof import('./../components/PartFormModal.vue')['default']
  const ProductDetailModal: typeof import('./../components/ProductDetailModal.vue')['default']
  const ProductFormModal: typeof import('./../components/ProductFormModal.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SideMenu: typeof import('./../components/SideMenu.vue')['default']
  const StatusBadge: typeof import('./../components/StatusBadge.vue')['default']
  const TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
  const TopBar: typeof import('./../components/TopBar.vue')['default']
  const WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
}